# Generated by Django 3.1 on 2021-11-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=140)),
                ('url_link', models.CharField(max_length=140, unique=True)),
                ('feed_site', models.CharField(max_length=140)),
                ('load_datetime', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('publish_date', models.CharField(max_length=140)),
                ('description', models.CharField(default='No value', max_length=200)),
            ],
        ),
    ]
