# Generated by Django 3.2.9 on 2021-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_feedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='feed_site_url',
            field=models.CharField(default='No value', max_length=200),
        ),
    ]
